# Generated by Django 5.0.4 on 2024-04-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsTariffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название тарифа')),
                ('description', models.TextField(verbose_name='Описание тарифа')),
                ('price', models.IntegerField(verbose_name='Цена тарифа')),
                ('image', models.ImageField(upload_to='photos/tariffs', verbose_name='Фото тарифа')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
    ]
