# Generated by Django 5.0.4 on 2024-04-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticstariffs',
            name='price',
            field=models.CharField(max_length=50, verbose_name='Цена тарифа'),
        ),
    ]
